services:
  scanner:
    build:
      context: ./scanner
      args:
        - MODEL_URL=${MODEL_URL}
    env_file:
      - .env
      - ./scanner/.env.scanner
    environment:
      - FLASK_PORT=${SCANNER_PORT}
      - MODEL_URL
      - MODEL_REFRESH_INTERVAL
      - LOG_LEVEL
    ports:
      - "${SCANNER_PORT}:${FLANNER_PORT}"
    volumes:
      - ./scanner/models:/app/models
      - ./scanner/logs:/app/logs
    restart: unless-stoppeds

  backend:
    build:
      context: ./backend
      args:
        - BACK_PORT=${BACK_PORT:-3000}  # Default to 3000 if not set
        - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5242880}
        - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${BACK_PORT:-3000}:${BACK_PORT:-3000}"
    depends_on:
      - scanner
    env_file:
      - .env
    restart: always
