version: "3.8"

services:
  scanner:
    build:
      context: ./scanner
      args:
        - FLASK_PORT=${FLASK_PORT:-5000}  # Default to 5000 if not set
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"  # Ensure fallback
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: ./backend
      args:
        - NODE_PORT=${NODE_PORT:-3000}  # Default to 3000 if not set
        - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10MB}
        - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    depends_on:
      - scanner
    env_file:
      - .env
    restart: always
