version: "3.8"

services:
  scanner:
    build:
      context: ./scanner
      args:
        - FLASK_PORT=${FLASK_PORT:-5000}  # Default to 5000 if not set
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"  # Ensure fallback
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: ./backend
      args:
        - BACK_PORT=${BACK_PORT:-3000}  # Default to 3000 if not set
        - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5242880}
        - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${BACK_PORT:-3000}:${BACK_PORT:-3000}"
    depends_on:
      - scanner
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - FRONT_PORT=${FRONT_PORT:-80}  # Default to 80 if not set
    ports:
      - "${FRONT_PORT:-80}:${FRONT_PORT:-80}"
    depends_on:
      - backend
    restart: always

